# This file contains default non-project-specific settings for 'stack', used
# in all projects.  For more information about stack's configuration, see
# http://docs.haskellstack.org/en/stable/yaml_configuration.html
#
templates:
  params:
    author-email: andrey.sergienko@gmail.com
    author-name: Andrii Sergiienko
#    category: value
#    copyright: value
    github-username: fycth
